data:
    output_bucket: ./data/out
    immigration_data_key: /data/18-83510-I94-Data-2016/i94_apr16_sub.sas7bdat
    airport_data_key: ./data/in/airport/airport-codes_csv.csv
    demographics_data_key: ./data/in/demographics/us-cities-demographics.csv
    temperatures_data_key: /data2/GlobalLandTemperaturesByCity.csv