aws:
  region: us-west-2
  s3:
    input_bucket: s3a://immigration-capstone-project
    output_bucket: s3a://immigration-capstone-project-output
    immigration_data_key: immigration/*.sas7bdat
    airport_data_key: airport/airport-codes_csv.csv
    demographics_data_key: demographics/us-cities-demographics.csv
    temperatures_data_key: temperatures/GlobalLandTemperaturesByCity.csv
  redshift:
    database: dev
    schema: public

airflow:
  redshift_conn_id: redshift
  aws_credentials_id: aws_credentials
